-- Cron jobs are scheduled manually after database setup
-- Run these commands in the Supabase SQL editor or via psql as postgres:
--
-- SELECT cron.schedule('weather-csv-sync', '*/15 * * * *', $$SELECT sync_weather_csv()$$);
-- SELECT cron.schedule('school-closings-sync', '*/5 * * * *', $$SELECT sync_school_closings()$$);
