-- Create vsimages bucket for virtual set AI-generated backgrounds
-- This bucket stores images generated by Imagen API for virtual studio sets

-- Create the bucket
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'vsimages',
  'vsimages',
  true,
  10485760, -- 10MB
  ARRAY['image/png', 'image/jpeg', 'image/gif', 'image/webp']::text[]
)
ON CONFLICT (id) DO NOTHING;

-- Allow authenticated users to upload to vsimages bucket
CREATE POLICY "Allow authenticated users to upload vsimages"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'vsimages');

-- Allow public read access to vsimages (for sharing URLs)
CREATE POLICY "Allow public read access to vsimages"
ON storage.objects
FOR SELECT
TO public
USING (bucket_id = 'vsimages');

-- Allow authenticated users to update their own uploads
CREATE POLICY "Allow authenticated users to update vsimages"
ON storage.objects
FOR UPDATE
TO authenticated
USING (bucket_id = 'vsimages');

-- Allow authenticated users to delete their uploads
CREATE POLICY "Allow authenticated users to delete vsimages"
ON storage.objects
FOR DELETE
TO authenticated
USING (bucket_id = 'vsimages');
